In [1]:
import logging
import json
import requests
from bs4 import BeautifulSoup

In [2]:
_headers = {
    'User-Agent': 'PostmanRuntime/7.24.1',
    'Accept': '*/*',
    'Connection': 'keep-alive'
}

_params = {
    'regNumber': '0346200001520000008'
}

_url_common_info = 'https://zakupki.gov.ru/epz/order/notice/ea44/view/common-info.html'
_url_supplier_results = 'https://zakupki.gov.ru/epz/order/notice/ea44/view/supplier-results.html'

In [4]:
def get_headers():
    return {
        'User-Agent': 'PostmanRuntime/7.24.1',
        'Accept': '*/*',
        'Connection': 'keep-alive'
    }

In [5]:
def get_params(regNumber):
    return {'regNumber': str(regNumber)}

In [11]:
def get_info(regNumber):
    _url_common_info = 'https://zakupki.gov.ru/epz/order/notice/ea44/view/common-info.html'
    response = requests.get(url=_url_common_info, headers=get_headers(), params=get_params(regNumber=regNumber))
    return response

In [ ]:
# 0346200001520000008

# 0848300062720000225
# 0146200003220000016
# 0137200001220002595

In [9]:
notificationNumber = '0146200003220000016'

In [12]:
z = get_info(notificationNumber)

In [15]:
def get_blocks(response):
    soup = BeautifulSoup(response.content, 'html.parser')
    return soup.find_all('div', class_='row blockInfo')

In [16]:
blocks = get_blocks(z)

In [35]:
def get_block_with(blocks, text: str):
    for block in blocks:
        if text in block.getText():
            return block
    return None

In [45]:
'Обеспечение заявки' in block.getText()

True

In [39]:
import pandas as pd
import numpy as np

In [38]:
df = pd.DataFrame(data={'Inn_post': ['0346200001520000008', '0848300062720000225', '0146200003220000016', '0137200001220002595']})
df

              Inn_post
0  0346200001520000008
1  0848300062720000225
2  0146200003220000016
3  0137200001220002595

In [40]:
df['raw_data'] = np.vectorize(get_info)(df['Inn_post'])

In [41]:
df

              Inn_post          raw_data
0  0346200001520000008  <Response [200]>
1  0848300062720000225  <Response [200]>
2  0146200003220000016  <Response [200]>
3  0137200001220002595  <Response [200]>

In [42]:
df['blocks'] = np.vectorize(get_blocks)(df['raw_data'])

In [43]:
df

,Inn_post,raw_data,blocks
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ..."
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ..."
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ..."
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ..."

In [46]:
df['Obesp_request'] = np.vectorize(get_block_with)(df['blocks'], 'Обеспечение заявки')

In [48]:
df

,Inn_post,raw_data,blocks,Obesp_request
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...","[\n, [\n, [Обеспечение заявки], \n, [\n, <span..."
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None

In [49]:
df['Obesp_contract'] = np.vectorize(get_block_with)(df['blocks'], 'Обеспечение исполнения контракта')

In [50]:
df

,Inn_post,raw_data,blocks,Obesp_request,Obesp_contract
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ..."
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...","[\n, [\n, [Обеспечение заявки], \n, [\n, <span...","[\n, [\n, [Обеспечение исполнения контракта], ..."
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [\n, <div class=""collapse__title"" ex..."

In [51]:
df['Obesp_garant'] = np.vectorize(get_block_with)(df['blocks'], 'Обеспечение гарантийных обязательств')

In [52]:
df

,Inn_post,raw_data,blocks,Obesp_request,Obesp_contract,Obesp_garant
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ...",None
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,"[\n, [\n, [\n, <div class=""collapse__title"" ex..."
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...","[\n, [\n, [Обеспечение заявки], \n, [\n, <span...","[\n, [\n, [Обеспечение исполнения контракта], ...",None
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [\n, <div class=""collapse__title"" ex...",None

In [74]:
df['BG_needed'] = np.logical_or(df['Obesp_request'], df['Obesp_contract'])

In [75]:
df['BG_needed'] = np.logical_or(df['BG_needed'], df['Obesp_garant'])

In [76]:
df

,Inn_post,raw_data,blocks,Obesp_request,Obesp_contract,Obesp_garant,BG_needed
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ..."
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,"[\n, [\n, [\n, <div class=""collapse__title"" ex...","[\n, [\n, [\n, <div class=""collapse__title"" ex..."
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...","[\n, [\n, [Обеспечение заявки], \n, [\n, <span...","[\n, [\n, [Обеспечение исполнения контракта], ...",None,"[\n, [\n, [Обеспечение заявки], \n, [\n, <span..."
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,None,None

In [72]:
df.loc[3, 'Obesp_contract'] = None

In [73]:
df

,Inn_post,raw_data,blocks,Obesp_request,Obesp_contract,Obesp_garant,BG_needed
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ..."
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,"[\n, [\n, [\n, <div class=""collapse__title"" ex...","[\n, [\n, [\n, <div class=""collapse__title"" ex..."
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...","[\n, [\n, [Обеспечение заявки], \n, [\n, <span...","[\n, [\n, [Обеспечение исполнения контракта], ...",None,"[\n, [\n, [Обеспечение заявки], \n, [\n, <span..."
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,None,"[\n, [\n, [\n, <div class=""collapse__title"" ex..."

In [79]:
def filter_if_needed(bg_data):
    if bg_data:
        return True
    else:
        return False

In [80]:
df['BG_filter'] = np.vectorize(filter_if_needed)(df['BG_needed'])

In [81]:
df

,Inn_post,raw_data,blocks,Obesp_request,Obesp_contract,Obesp_garant,BG_needed,BG_filter
0,0346200001520000008,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ...",None,"[\n, [\n, [Обеспечение исполнения контракта], ...",True
1,0848300062720000225,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,"[\n, [\n, [\n, <div class=""collapse__title"" ex...","[\n, [\n, [\n, <div class=""collapse__title"" ex...",True
2,0146200003220000016,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...","[\n, [\n, [Обеспечение заявки], \n, [\n, <span...","[\n, [\n, [Обеспечение исполнения контракта], ...",None,"[\n, [\n, [Обеспечение заявки], \n, [\n, <span...",True
3,0137200001220002595,<Response [200]>,"[[\n, [\n, <h2 class=""blockInfo__title"">Общая ...",None,None,None,None,False